name: Build

on: 
  workflow_dispatch:
    inputs:
      Linux:
        description: 'Build on Linux - Ubuntu'
        type: boolean
      Macos:
        description: 'Build on Macos'
        type: boolean
      Windows:
        description: 'Build on Windows'
        type: boolean

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bin_name: davinci-cleaner-linux-x64
            bin_path: davinci-cleaner
            will_run: ${{ inputs.Linux }}
          - os: macos-latest
            bin_name: davinci-cleaner-macos-x64
            bin_path: davinci-cleaner
            will_run: ${{ inputs.Macos }}
          - os: windows-latest
            bin_name: davinci-cleaner-windows-x64.exe
            bin_path: davinci-cleaner.exe
            will_run: ${{ inputs.Windows }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      if: ${{ matrix.will_run }}
      with:
        submodules: true

    - uses: Swatinem/rust-cache@v2
        
    - name: Build CLI
      if: ${{ matrix.will_run }}
      run: cargo build --verbose --release
      
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.will_run }}
      with:
        name: ${{ matrix.bin_name }}
        path: target/release/${{ matrix.bin_path }}

